// Client Stub for the Rental Service


import ballerina/io;

public function clientStub() {
    io:println("This is the client stub of the rental accommodation system t be generated by the proto file");
}