// Server Stub for the Rental Service

import ballerina/io;

public function serverStub() {
    io:println("This is the server side of the rental accommodation system to be generated by the proto file");
}